### ISSUE TITLE
Annotating: only specify annotation id once?

### ISSUE THREAD

**Issue by karlicoss** [nickpascucci/verso#1]
Would be nice if you don't have to repeat annotation id for the closing 'tag'?
E.g.:

```
def main():
    #@!annotation_1
    print("Hello")
    print("World")
    #!@
    print("!")
    #@!annotation_2
    sys.exit(1)
    #!@
```

If annotations are overlapping then you can still specify the id so it's parsed correctly

```
def main():
    #@!annotation_1
    print("Hello!")
    #@!annotation_2
    print("World")
    #!@annotation_1
    print("!")
    sys.exit(1)
    #!@annotation_2
```

Btw, `#!` is a shebang, so it might make people nervous seeing it all around their code! Maybe a different symbol instead of bang? :)

**Comment by karlicoss** [comment]
Hm, actually I tried it and it seems that it already doesn't check id for closing tag?

**Comment by nickpascucci** [comment]
You're right, right now it's not checking for the ID in the close tag, and you're also right that the intent is to provide a way to match up delimiters in the source file. Right now the reader isn't that sophisticated, but I do want to add that ability.

I'm open to suggestions on other symbols to use. `@!` was nice to type and I couldn't find it used in common languages but the collision with shebangs from `!@` is a problem. I could be convinced to do something along the lines of `@begin{id}` or similar. It's more verbose, but also more explicit. (In the future this should probably be configurable.)

**Comment by nickpascucci** [comment]
Fixed the shebang issue, for now, by switching to `@<`/`@>` for the annotations in c183c75.
