### ISSUE TITLE
Nice project.

### ISSUE THREAD

**Issue by martinmr** [nickpascucci/verso#10]
Not really an issue, but simply a comment. I've been thinking of turning the documentation for my open-source project (located at https://trane-project.github.io/) into some sort of literary programming book, and I was brainstorming something that could work with mdbook, which is what I am using right now. I came up with something similar to this. Something that preprocessed the documentation files and attached the sections from the code.

Glad to see that it's already been made and fits my purposes. Still have to try it out, but it looks very promising.

**Comment by nickpascucci** [comment]
Thanks for the kind message! I'm glad `verso|recto` looks useful. Let me know if you hit any issues, and enjoy your project — it looks quite interesting!

**Comment by martinmr** [comment]
Thanks. I had a chance to play with it today, and it fits perfectly into what I was envisioning. The hardest part was to fiddle with the `find` command to create the list of source and markdown files, but once I figured that out it integrated perfectly into mdbook. I still have not published anything written on it yet, but that comes later. Thanks again for the tool.
