### ISSUE TITLE
Identifiers cannot use all of the characters that docs say they can

### ISSUE THREAD

**Issue by mmontone** [nickpascucci/verso#6]
Hello.

Documentation says: "The ID can be any string of non-whitespace characters".

But when I try to use IDs with "special" characters, like '/', the Annotations are not parsed completly.

For example,

I have this IDs: `api/definition` and `api/implementation`.

But then when I run verso, Verso stops reading at the special character ('/' in this case):

```
Read annotation api
Read annotation api
```

but should have read:

```
Read annotation api/definition
Read annotation api/implementation
```

**Comment by nickpascucci** [comment]
Thanks for the bug report! You're right, the current parser only looks for alphanumeric identifiers. I'll give it a think and see if I can expand that character set a bit. I _think_ slashes should be fine; periods (`.`) are out as we use them for reference insertions in `recto`.

**Comment by nickpascucci** [comment]
This issue should be fixed in `verso` v0.1.1; feel free to re-open this issue if you're still having trouble.

**Comment by nickpascucci** [comment]
(Also related: 2e0d273)

**Comment by mmontone** [comment]
Great. Thanks!
