### ISSUE TITLE
Configurable Block Open / Close character sequences?

### ISSUE THREAD

**Issue by d023604** [nickpascucci/verso#7]
I've been using verso with the ABAP programming language and have stumbled across a few cases where the block open character sequence @< is used in ABAP code. This right royally confuses recto / verso.  I've not experienced collisions with other symbols. 

I wonder about the interest in making the block open and close sequences able to be read from a file with a fallback to the standard sequences if optional configuration content is not available?

**Comment by nickpascucci** [comment]
I tried to pick a combination of symbols that wouldn't have collisions, but that's clearly impossible to do! While a config file is a bit more than I want for these tools, I do think this is a reasonable feature request so I've added support for overriding the symbology using environment variables in 7c2e64a.

Documentation updates are in the README, so have a peek and see if this suits your needs.

**Comment by d023604** [comment]
Hello Nickpascucci/Verso,

Wonderful! That will do the trick nicely.

Kind Regards
Andrew
