### ISSUE TITLE
Add Command Line help to recto and verso

### ISSUE THREAD

**Issue by d023604** [nickpascucci/verso#9]
Whilst the readme for the crate verso is clear on the arguments that recto and verso take, it would be nice to support the argument --help or -h to output the usage of recto and verso.

This might be achieved by using the clap crate or a similar CLI argument parsing tool.

**Comment by nickpascucci** [comment]
Hey, thanks for raising this. At the moment, on my machine, `verso` and `recto` compile to very small binaries: `verso` is just 531k, whereas `recto` is a bit beefier at 1.8M. While `clap` is a great library and can make it very easy to add new CLI features, I think that it's overkill here as these tools are not intended to grow much past their current feature set.

However, it's true that the help could be improved so I've added a little text drawn from the README which is printed if argument parsing fails. Hopefully that is a happy medium!

**Comment by d023604** [comment]
Thanks for another pragmatic solution. Appreciate it.
